name: Rust Docs to Wiki

# This workflow extracts documentation from Rust source code and updates the GitHub wiki.
# 
# IMPORTANT: This workflow requires a personal access token (PAT) with 'workflow' scope
# to push changes to the wiki repository. The default GITHUB_TOKEN doesn't have wiki permissions.
# 
# Setup instructions:
# 1. Create a personal access token with 'workflow' scope at:
#    https://github.com/settings/tokens
# 2. Add the token as a repository secret named 'WIKI_TOKEN' at:
#    https://github.com/YOUR_USERNAME/YOUR_REPO/settings/secrets/actions
# 
# If you don't want to use a PAT, you can comment out the 'Clone Wiki Repository' step
# and uncomment the artifact upload step to manually update the wiki.

on:
  push:
    branches: [ main, master ]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - '.github/workflows/rust-docs-to-wiki.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  extract-docs-and-update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Install mdBook
        run: cargo install mdbook

      - name: Generate documentation
        run: |
          # Generate standard docs
          cargo doc --no-deps
          
          # Create a directory for markdown docs
          mkdir -p wiki-content
          
          # Extract HTML docs for later parsing
          mkdir -p target/doc-extract
          cp -r target/doc/* target/doc-extract/
          
          # For each Rust file, extract doc comments directly
          find src -name "*.rs" | while read -r file; do
            # Get relative path for wiki structure
            rel_path=${file#src/}
            rel_path=${rel_path%.rs}
            dir_path="wiki-content/${rel_path%/*}"
            
            # Create directory if it doesn't exist
            mkdir -p "$dir_path"
            
            # Extract doc comments and convert to markdown
            echo "# $(basename ${file%.rs})" > "wiki-content/${rel_path}.md"
            echo "" >> "wiki-content/${rel_path}.md"
            echo "Path: \`$file\`" >> "wiki-content/${rel_path}.md"
            echo "" >> "wiki-content/${rel_path}.md"
            
            # Extract module-level documentation
            module_docs=$(grep -A 5 "//!" "$file" | sed 's/\/\/\!\s*//' | sed '/^--$/d')
            if [ -n "$module_docs" ]; then
              echo "## Module Documentation" >> "wiki-content/${rel_path}.md"
              echo "" >> "wiki-content/${rel_path}.md"
              echo "$module_docs" >> "wiki-content/${rel_path}.md"
              echo "" >> "wiki-content/${rel_path}.md"
            fi
            
            # Add section for public items
            echo "## Public Items" >> "wiki-content/${rel_path}.md"
            echo "" >> "wiki-content/${rel_path}.md"
            
            # Extract function/struct/trait names and doc comments
            grep -n "^pub " "$file" | while read -r line; do
              line_num=$(echo "$line" | cut -d: -f1)
              item=$(echo "$line" | cut -d: -f2-)
              
              # Get doc comments above this item (/// style comments)
              prev_lines=$(head -n $((line_num-1)) "$file" | tac | sed -n '/\/\/\//p' | tac)
              
              if [ -n "$prev_lines" ]; then
                echo "### $(echo "$item" | sed 's/pub //' | sed 's/{.*//' | sed 's/(.*//' | tr -d '\n')" >> "wiki-content/${rel_path}.md"
                echo "" >> "wiki-content/${rel_path}.md"
                echo "$prev_lines" | sed 's/\/\/\/\s*//' >> "wiki-content/${rel_path}.md"
                echo "" >> "wiki-content/${rel_path}.md"
                echo '```rust' >> "wiki-content/${rel_path}.md"
                echo "$item" | sed 's/\s*{.*$//' >> "wiki-content/${rel_path}.md"
                echo '```' >> "wiki-content/${rel_path}.md"
                echo "" >> "wiki-content/${rel_path}.md"
              fi
            done
          done
          
          # Create Home.md
          echo "# ${GITHUB_REPOSITORY#*/} Documentation" > wiki-content/Home.md
          echo "" >> wiki-content/Home.md
          echo "This wiki contains automatically generated documentation from the Rust codebase." >> wiki-content/Home.md
          echo "" >> wiki-content/Home.md
          echo "## Modules" >> wiki-content/Home.md
          
          # Add links to files (excluding Home.md)
          find wiki-content -type f -name "*.md" ! -name "Home.md" | sort | while read -r file; do
            rel_file=${file#wiki-content/}
            title=$(head -n 1 "$file" | sed 's/^# //')
            echo "* [$title]($rel_file)" >> wiki-content/Home.md
          done

      - name: Setup Git for Wiki
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone Wiki Repository
        run: |
          # Use PAT for wiki push (needs to be set in repository secrets)
          git clone https://${{ secrets.WIKI_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki-repo
          
          # Copy new content to wiki repository
          cp -r wiki-content/* wiki-repo/
          
          cd wiki-repo
          git add .
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update documentation from Rust code (${GITHUB_SHA:0:7})"
            git push
          fi

      - name: Upload Markdown as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wiki-docs
          path: wiki-content/
